server {
    listen 3000;

    location /rest/v1/ {
        rewrite ^/rest/v1/(.*) /$1 break;
        proxy_pass http://postgrest:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /health {
        return 200 "ok";
        add_header Content-Type text/plain;
    }
}
